# Generated by Django 5.2.8 on 2025-11-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('umbral_ocupacion', models.PositiveIntegerField(help_text='Porcentaje mínimo, ej: 60')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ventana_inicio', models.TimeField()),
                ('ventana_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='administracion.cooperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasajero_nombre', models.CharField(max_length=100)),
                ('pasajero_cedula', models.CharField(max_length=10)),
                ('fecha_viaje', models.DateField()),
                ('asiento', models.PositiveIntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='administracion.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('duracion_min', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('hora_salida', models.TimeField()),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='administracion.cooperativa')),
            ],
        ),
    ]
